name: 'GitHub Actions'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    name: 'tests'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: npm run test
    - run: npm run build
    - name: Verify generated files are up to date
      run: git add . -N && git diff --ignore-cr-at-eol --exit-code

  prettier:
    name: 'prettier'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run fmt:check
